# Generated by Django 3.0.3 on 2020-04-03 03:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseOilInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_del', models.BooleanField(default=False)),
                ('root_path', models.CharField(max_length=100)),
                ('case_path', models.CharField(max_length=100)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('forecast_date', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('ext', models.CharField(max_length=20)),
                ('case_name', models.CharField(max_length=50)),
                ('case_desc', models.CharField(max_length=500)),
                ('case_code', models.CharField(editable=False, max_length=50, unique=True)),
                ('area', models.IntegerField(choices=[(-1, 'NULL'), (0, 'NORTHWEST'), (1, 'CHINASEA'), (2, 'EASTCHINASEA'), (3, 'BOHAISEA'), (4, 'INDIAN'), (5, 'SOUTHCHINASEA')], default=-1)),
                ('lat', models.FloatField(null=True, verbose_name='经度')),
                ('lon', models.FloatField(null=True, verbose_name='纬度')),
                ('radius', models.FloatField(null=True, verbose_name='释放半径')),
                ('nums', models.IntegerField(null=True, verbose_name='释放粒子数')),
                ('simulation_duration', models.FloatField(null=True, verbose_name='模拟时长')),
                ('simulation_step', models.FloatField(null=True, verbose_name='模拟步长')),
                ('console_step', models.FloatField(null=True, verbose_name='输出步长')),
                ('current_nondeterminacy', models.FloatField(null=True, verbose_name='流场不确定性')),
                ('wind_nondeterminacy', models.FloatField(default=0, null=True, verbose_name='风场不确定性')),
                ('equation', models.IntegerField(choices=[(0, 'Euler'), (1, 'Runge'), (2, '4Runge')], null=True, verbose_name='求解方法')),
                ('wind_coefficient', models.FloatField(null=True, verbose_name='风偏系数')),
                ('wind_dir', models.FloatField(null=True, verbose_name='风偏角度')),
            ],
            options={
                'db_table': 'user_caseoilinfo',
            },
        ),
        migrations.CreateModel(
            name='CaseRescueInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_del', models.BooleanField(default=False)),
                ('root_path', models.CharField(max_length=100)),
                ('case_path', models.CharField(max_length=100)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('forecast_date', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('ext', models.CharField(max_length=20)),
                ('case_name', models.CharField(max_length=50)),
                ('case_desc', models.CharField(max_length=500)),
                ('case_code', models.CharField(editable=False, max_length=50, unique=True)),
                ('area', models.IntegerField(choices=[(-1, 'NULL'), (0, 'NORTHWEST'), (1, 'CHINASEA'), (2, 'EASTCHINASEA'), (3, 'BOHAISEA'), (4, 'INDIAN'), (5, 'SOUTHCHINASEA')], default=-1)),
                ('lat', models.FloatField(null=True, verbose_name='经度')),
                ('lon', models.FloatField(null=True, verbose_name='纬度')),
                ('radius', models.FloatField(null=True, verbose_name='释放半径')),
                ('nums', models.IntegerField(null=True, verbose_name='释放粒子数')),
                ('simulation_duration', models.FloatField(null=True, verbose_name='模拟时长')),
                ('simulation_step', models.FloatField(null=True, verbose_name='模拟步长')),
                ('console_step', models.FloatField(null=True, verbose_name='输出步长')),
                ('current_nondeterminacy', models.FloatField(null=True, verbose_name='流场不确定性')),
                ('wind_nondeterminacy', models.FloatField(default=0, null=True, verbose_name='风场不确定性')),
                ('equation', models.IntegerField(choices=[(0, 'Euler'), (1, 'Runge'), (2, '4Runge')], null=True, verbose_name='求解方法')),
                ('goods_type', models.IntegerField(null=True, verbose_name='失事物类型')),
            ],
            options={
                'db_table': 'user_caserescueinfo',
            },
        ),
        migrations.CreateModel(
            name='JobInfo',
            fields=[
                ('is_del', models.BooleanField(default=False)),
                ('area', models.IntegerField(choices=[(-1, 'NULL'), (0, 'NORTHWEST'), (1, 'CHINASEA'), (2, 'EASTCHINASEA'), (3, 'BOHAISEA'), (4, 'INDIAN'), (5, 'SOUTHCHINASEA')], default=-1)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('job_celery_id', models.CharField(max_length=200)),
                ('case_code', models.CharField(editable=False, max_length=50, unique=True)),
                ('gmt_create', models.DateTimeField(auto_now_add=True)),
                ('gmt_modified', models.DateTimeField(auto_now=True)),
                ('type', models.IntegerField(choices=[(0, 'oil'), (1, 'rescue')], default=0)),
            ],
            options={
                'db_table': 'user_jobinfo',
            },
        ),
        migrations.CreateModel(
            name='JobUserRate',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('rate', models.IntegerField()),
                ('state', models.IntegerField(choices=[(1, 'RUNNING'), (2, 'COMPLETED'), (3, 'WAITTING'), (4, 'ERROR'), (5, 'UNUSED')], default=2)),
                ('gmt_create', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('gmt_modified', models.DateTimeField(default=django.utils.timezone.now)),
                ('jid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.JobInfo')),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_jobuserrate',
            },
        ),
        migrations.CreateModel(
            name='AuthRescueRela',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('did', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.CaseRescueInfo')),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_authrescue_rela',
            },
        ),
        migrations.CreateModel(
            name='AuthOilRela',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('did', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.CaseOilInfo')),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_authoil_rela',
            },
        ),
    ]
