# Generated by Django 3.0.3 on 2020-02-29 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='caseoilinfo',
            name='wind_nondeterminacy',
            field=models.FloatField(default=0, null=True, verbose_name='风场不确定性'),
        ),
        migrations.AddField(
            model_name='caserescueinfo',
            name='wind_nondeterminacy',
            field=models.FloatField(default=0, null=True, verbose_name='风场不确定性'),
        ),
    ]
