# Generated by Django 3.0.3 on 2020-04-07 06:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskUserModel',
            fields=[
                ('root_path', models.CharField(max_length=100)),
                ('case_path', models.CharField(max_length=100)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('forecast_date', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('ext', models.CharField(max_length=20)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('product_type', models.IntegerField(choices=[(1, 'DAILY_CURRENT_BHS'), (2, 'DAILY_CURRENT_ECS'), (3, 'DAILY_CURRENT_IND'), (4, 'DAILY_CURRENT_SCS'), (5, 'DAILY_CURRENT_NWP'), (6, 'DAILY_WIND_WRF')], default=1)),
                ('state', models.IntegerField(choices=[(1, 'RUNNING'), (2, 'COMPLETED'), (3, 'WAITTING'), (4, 'ERROR'), (5, 'UNUSED')], default=5)),
            ],
            options={
                'db_table': 'user_taskinfo',
            },
        ),
        migrations.AlterField(
            model_name='jobinfo',
            name='type',
            field=models.IntegerField(choices=[(0, 'oil'), (1, 'rescue'), (2, 'coverage')], default=0),
        ),
    ]
