# Generated by Django 3.0.3 on 2020-04-15 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200414_2018'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskusermodel',
            name='product_type',
        ),
        migrations.AddField(
            model_name='taskusermodel',
            name='coverage_id',
            field=models.IntegerField(default=-1),
        ),
    ]
