# Generated by Django 3.0.3 on 2020-04-16 09:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20200416_1503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caseoilinfo',
            name='forecast_date',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name='caserescueinfo',
            name='forecast_date',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name='taskusermodel',
            name='forecast_date',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
    ]
