# Generated by Django 3.0.3 on 2020-04-28 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20200416_1700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caseoilinfo',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
