# Generated by Django 3.0.3 on 2020-05-12 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20200428_0220'),
    ]

    operations = [
        migrations.AddField(
            model_name='caseoilinfo',
            name='file_name',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='caseoilinfo',
            name='full_path',
            field=models.CharField(default=None, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='caserescueinfo',
            name='file_name',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='caserescueinfo',
            name='full_path',
            field=models.CharField(default=None, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='taskusermodel',
            name='file_name',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='taskusermodel',
            name='full_path',
            field=models.CharField(default=None, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='caseoilinfo',
            name='case_desc',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='caserescueinfo',
            name='case_desc',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='jobinfo',
            name='job_celery_id',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
