# Generated by Django 3.0.3 on 2020-05-12 07:51

import computed_property.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20200512_0130'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='caserescueinfo',
            name='file_name',
        ),
        migrations.RemoveField(
            model_name='caserescueinfo',
            name='full_path',
        ),
        migrations.RemoveField(
            model_name='taskusermodel',
            name='file_name',
        ),
        migrations.RemoveField(
            model_name='taskusermodel',
            name='full_path',
        ),
        migrations.AddField(
            model_name='caseoilinfo',
            name='absolute_path',
            field=models.CharField(default=None, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='caseoilinfo',
            name='file_name',
            field=computed_property.fields.ComputedCharField(compute_from='get_file_name', default=None, editable=False, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='caseoilinfo',
            name='full_path',
            field=computed_property.fields.ComputedCharField(compute_from='get_full_path', default=None, editable=False, max_length=200, null=True),
        ),
    ]
