# Generated by Django 3.0.3 on 2020-04-27 13:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('geo', '0013_auto_20200427_1345'),
        ('users', '0006_auto_20200416_1700'),
    ]

    operations = [
        migrations.CreateModel(
            name='RelaCaseOilCoverage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('case_id', models.ForeignKey(default=-1, on_delete=django.db.models.deletion.SET_DEFAULT, to='users.CaseOilInfo')),
                ('wind_id', models.ForeignKey(default=-1, on_delete=django.db.models.deletion.SET_DEFAULT, to='geo.CoverageModel')),
            ],
            options={
                'db_table': 'rela_case_oil',
            },
        ),
    ]
