# Generated by Django 3.0.3 on 2020-04-28 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rela', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='relacaseoilcoverage',
            name='current_id',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='relacaseoilcoverage',
            name='case_id',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='relacaseoilcoverage',
            name='wind_id',
            field=models.IntegerField(default=-1),
        ),
    ]
