# Generated by Django 3.0.3 on 2020-04-28 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rela', '0002_auto_20200428_0248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relacaseoilcoverage',
            name='current_id',
            field=models.IntegerField(default=-1, null=True),
        ),
        migrations.AlterField(
            model_name='relacaseoilcoverage',
            name='wind_id',
            field=models.IntegerField(default=-1, null=True),
        ),
    ]
