# Generated by Django 3.0.3 on 2020-05-12 01:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rela', '0003_auto_20200428_0646'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RelaCaseOilCoverage',
            new_name='RelaCaseOilCoverageModel',
        ),
    ]
