# Generated by Django 3.0.5 on 2020-04-15 11:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CoverageModel',
            fields=[
                ('is_del', models.BooleanField(default=False)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('desc', models.CharField(max_length=500)),
                ('root_path', models.CharField(max_length=100)),
                ('relative_path', models.CharField(max_length=100)),
                ('file_name', models.CharField(max_length=50)),
                ('file_size', models.FloatField(default=0.0)),
                ('create_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('dimessions', models.CharField(default='', max_length=500)),
                ('variables', models.CharField(default='', max_length=500)),
                ('is_original', models.BooleanField(default=True)),
                ('coverage_type', models.IntegerField(default=-1)),
                ('coverage_area', models.IntegerField(default=-1)),
            ],
            options={
                'db_table': 'geo_coverageinfo',
            },
        ),
    ]
