# Generated by Django 3.0.3 on 2020-04-03 03:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CoverageModel',
            fields=[
                ('is_del', models.BooleanField(default=False)),
                ('area', models.IntegerField(choices=[(-1, 'NULL'), (0, 'NORTHWEST'), (1, 'CHINASEA'), (2, 'EASTCHINASEA'), (3, 'BOHAISEA'), (4, 'INDIAN'), (5, 'SOUTHCHINASEA')], default=-1)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('root_path', models.CharField(max_length=100)),
                ('relative_path', models.CharField(max_length=100)),
                ('file_name', models.CharField(max_length=50)),
                ('file_size', models.FloatField(default=0.0)),
                ('create_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('dimessions', models.CharField(default='', max_length=500)),
                ('variables', models.CharField(default='', max_length=500)),
            ],
            options={
                'db_table': 'geo_coverageinfo',
            },
        ),
    ]
