# Generated by Django 3.0.3 on 2020-04-07 06:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coveragemodel',
            name='desc',
            field=models.CharField(default=django.utils.timezone.now, max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='coveragemodel',
            name='is_original',
            field=models.BooleanField(default=True),
        ),
    ]
