# Generated by Django 3.0.3 on 2020-04-14 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0002_auto_20200407_1458'),
    ]

    operations = [
        migrations.AddField(
            model_name='coveragemodel',
            name='coverage_area',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='coveragemodel',
            name='coverage_type',
            field=models.IntegerField(default=-1),
        ),
    ]
