# Generated by Django 3.0.3 on 2020-04-15 02:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0003_auto_20200414_2020'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coveragemodel',
            name='area',
        ),
    ]
