# Generated by Django 3.0.3 on 2020-04-16 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0004_remove_coveragemodel_area'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeoStoreModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_space', models.CharField(default='default', max_length=50)),
                ('store_name', models.CharField(default='default', max_length=100)),
                ('store_type', models.IntegerField(choices=[(-1, 'DEFAULT'), (301, 'NetCDF')], default=-1)),
                ('enabled', models.BooleanField(default=True)),
                ('is_del', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'geo_storeinfo',
            },
        ),
        migrations.CreateModel(
            name='GeoWorkSpaceModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_space', models.CharField(default='default', max_length=50)),
                ('work_space_url', models.CharField(default='default', max_length=100)),
            ],
            options={
                'db_table': 'geo_workspaceinfo',
            },
        ),
        migrations.CreateModel(
            name='LayerModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_space', models.CharField(default='default', max_length=50)),
                ('title', models.CharField(default='default', max_length=100)),
                ('store_name', models.CharField(default='default', max_length=100)),
                ('layer_name', models.CharField(default='default', max_length=50)),
            ],
            options={
                'db_table': 'geo_layerinfo',
            },
        ),
    ]
