# Generated by Django 3.0.3 on 2020-04-16 02:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0007_layermodel_is_del'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LayerModel',
            new_name='GeoLayerModel',
        ),
        migrations.CreateModel(
            name='RGeoInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('layer', models.ForeignKey(default=-1, on_delete=django.db.models.deletion.SET_DEFAULT, to='geo.GeoLayerModel')),
                ('store', models.ForeignKey(default=-1, on_delete=django.db.models.deletion.SET_DEFAULT, to='geo.GeoStoreModel')),
                ('ws', models.ForeignKey(default=-1, on_delete=django.db.models.deletion.SET_DEFAULT, to='geo.GeoWorkSpaceModel')),
            ],
            options={
                'db_table': 'rela_geo_base',
            },
        ),
    ]
