# Generated by Django 3.0.3 on 2020-04-16 02:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20200415_1009'),
        ('geo', '0008_auto_20200416_1050'),
    ]

    operations = [
        migrations.AddField(
            model_name='rgeoinfo',
            name='task',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.SET_DEFAULT, to='users.TaskUserModel'),
        ),
    ]
