# Generated by Django 3.0.3 on 2020-04-16 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0010_rgeoinfo_coverage'),
    ]

    operations = [
        migrations.AddField(
            model_name='geolayermodel',
            name='style_name',
            field=models.CharField(default='default', max_length=50),
        ),
    ]
