# Generated by Django 3.0.3 on 2020-04-27 13:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0012_geoserverbasemodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='coveragemodel',
            name='gmt_forecast_end',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='coveragemodel',
            name='gmt_forecast_start',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
