# Generated by Django 3.0.3 on 2020-04-14 08:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DictBaseModel',
            fields=[
                ('code', models.IntegerField(default=-1, primary_key=True, serialize=False)),
                ('pid', models.IntegerField(default=-1)),
                ('type_code', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=20)),
                ('desc', models.CharField(max_length=200)),
                ('val', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'dict_base',
            },
        ),
        migrations.AlterField(
            model_name='selectmodel',
            name='type_select',
            field=models.IntegerField(choices=[(0, 'NULL'), (1, 'OPTIONWRECK'), (2, 'EQUATION'), (3, 'NULL'), (4, 'COVERAGE_TYPE'), (5, 'COVERAGE_AREA')], default=0),
        ),
        migrations.AddField(
            model_name='selectmodel',
            name='did',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.SET_DEFAULT, to='common.DictBaseModel'),
        ),
    ]
